# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: publish-maven-package-api
concurrency:
  group: 'publish-maven-package-api'
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-m2-

    - name: build framework modules
      run: | #bash
        mvn -Pdeveloper -Dsimulator -DskipTests clean install  -pl api

    - name: deploy api module
      run: | #bash
        mvn -Pdeveloper -Dsimulator -DskipTests deploy -pl api
      env:
        GITHUB_TOKEN: ${{ github.token }}
